Feature clear-reports
tovernaar123/Exp-discord-bot pull request #26
Opened 2020-12-25 01:15 UTC by aldldl

Added the clear-reports feature to the bot. Also corrected usage for "Players online"

2020-12-25 13:54 UTC, tovernaar123 requested changes
The overall logic is good an look clean just some small things

2020-12-25 13:54 UTC, tovernaar123 commented on commands/playersonline.js
> +            msg.channel.send(`Please pick a server first just a number (1-8). Usage: \`${prefix} po <server#>\` or \`${prefix} po all\``)
i dont think playersonline.js has prefix as a variable so this wont work

2020-12-25 13:54 UTC, tovernaar123 commented on commands/playersonline.js
> +            msg.channel.send(`No second argument is needed (1-8). correct usage: \`${prefix} po <server#>\` or \`${prefix} po all\``)
i dont think playersonline.js has prefix as a variable so this wont work

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +    await msg.channel.send(`*Please make sure you have the correct username and a report was issued in #reports.* Server replies complete even if user does not exist. Server replied: ${res} By: ${msg
this seems like a test wall but that might just be me

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +    let reportChan = msg.guild.channels.cache.get('368812365594230788'); // Reports channel is "368812365594230788" for exp // Reports Channel is "764881627893334047" for test server
why is this here?

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +        const author = msg.author.username; //find author
might wanna use displayname

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +            msg.channel.send('Please pick a server first (**just the number 1-8**). \`<Server#> <username> <reason>\`');
msg.channel.send is a promise so must either be awaited or caught with internal error

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +            msg.channel.send(`You need to tell us who you would like to clear for us to be able to clear-all \`<#> <username> <reason>\``);
msg.channel.send is a promise so must either be awaited or caught with internal error

2020-12-25 13:54 UTC, tovernaar123 commented on commands/clear_reports.js
> +            msg.channel.send(`Please put a reason for the report chan. \`<#> <username> <reason>\``);
msg.channel.send is a promise so must either be awaited or caught with internal error

2020-12-25 15:32 UTC, PHIDIAS0303 commented on commands/clear_reports.js
> +        const author = msg.author.username; //find author
or do it with 24

2020-12-28 23:38 UTC, aldldl commented on commands/playersonline.js
> +            msg.channel.send(`Please pick a server first just a number (1-8). Usage: \`${prefix} po <server#>\` or \`${prefix} po all\``)
added `let prefix = process.env.PREFIX;` in

2020-12-28 23:39 UTC, aldldl commented on commands/clear_reports.js
> +    await msg.channel.send(`*Please make sure you have the correct username and a report was issued in #reports.* Server replies complete even if user does not exist. Server replied: ${res} By: ${msg
> this seems like a test wall but that might just be me

What is a test wall?

2020-12-28 23:40 UTC, aldldl commented on commands/clear_reports.js
> +    let reportChan = msg.guild.channels.cache.get('368812365594230788'); // Reports channel is "368812365594230788" for exp // Reports Channel is "764881627893334047" for test server
```suggestion
```
Will Remove, was going to report it but decided later not to because Cools' system picks it up ingame.

2020-12-28 23:41 UTC, aldldl commented on commands/clear_reports.js
> +        const author = msg.author.username; //find author
Do what with 24?

2020-12-28 23:47 UTC, aldldl commented on commands/clear_reports.js
> +            msg.channel.send('Please pick a server first (**just the number 1-8**). \`<Server#> <username> <reason>\`');
I can't find any docs that say channel.send() is a primise unless constructed with await - I know I'm missing something but I've never once catched a message.channel.send() (does not mean I'm doing it right though).

2020-12-29 16:14 UTC, tovernaar123 commented on commands/clear_reports.js
> +    await msg.channel.send(`*Please make sure you have the correct username and a report was issued in #reports.* Server replies complete even if user does not exist. Server replied: ${res} By: ${msg
text wall

2020-12-29 16:15 UTC, tovernaar123 commented on commands/clear_reports.js
> +        const author = msg.author.username; //find author
just fix it :P

2020-12-29 16:16 UTC, tovernaar123 commented on commands/clear_reports.js
> +            msg.channel.send('Please pick a server first (**just the number 1-8**). \`<Server#> <username> <reason>\`');
no becuase they normanly dont error but msg.channel.send returns an promise so if it were to some how fail it would need to caugth with .catch

2020-12-30 20:43 UTC, aldldl commented on commands/clear_reports.js
> +    await msg.channel.send(`*Please make sure you have the correct username and a report was issued in #reports.* Server replies complete even if user does not exist. Server replied: ${res} By: ${msg
Well in game there is no test for completion or success because if you run the command it replies completed. I put in an issue for Cool to fix but I dont think its priority right now. I plan to fix it as soon as we can get it fixed ingame. @tovernaar123

2020-12-30 20:44 UTC, aldldl commented on commands/clear_reports.js
> +        const author = msg.author.username; //find author
```suggestion
        const author = msg.author.displayName; //find author
```
I don't even think I use it but I fixed it anyway ;)

2020-12-30 20:48 UTC, aldldl commented on commands/clear_reports.js
> +            msg.channel.send('Please pick a server first (**just the number 1-8**). \`<Server#> <username> <reason>\`');
```suggestion
            msg.channel.send('Please pick a server first (**just the number 1-8**). \`<Server#> <username> <reason>\`')
            .catch((err) => { internal_error(err); return });
```
@tovernaar123 like this?

2020-12-30 20:49 UTC, aldldl commented on commands/clear_reports.js
> +            msg.channel.send(`You need to tell us who you would like to clear for us to be able to clear-all \`<#> <username> <reason>\``);
```suggestion
            msg.channel.send(`You need to tell us who you would like to clear for us to be able to clear-all \`<#> <username> <reason>\``)
            .catch((err) => { internal_error(err); return });
```
and this

2020-12-30 20:50 UTC, aldldl commented on commands/clear_reports.js
> +            msg.channel.send(`Please put a reason for the report chan. \`<#> <username> <reason>\``);
```suggestion
            msg.channel.send(`Please put a reason for the report chan. \`<#> <username> <reason>\``)
            .catch((err) => { internal_error(err); return });
```
and this

2020-12-31 14:47 UTC, tovernaar123 approved these changes
all good now

2020-12-31 14:52 UTC, merged