Create playerdata.js
tovernaar123/Exp-discord-bot pull request #30
Opened 2021-02-09 17:18 UTC by aldldl

Create the file for playerdata command. Will update file shortly

2021-02-26 21:30 UTC, aldldl commented
crap is it master or dev I want to use. I think its master because Dev still has Tovs log stuff in it

2021-02-27 12:02 UTC, tovernaar123 commented
if you want it to run you shood master

2021-02-27 12:27 UTC, tovernaar123 requested changes
Please look at my comments

2021-02-27 12:27 UTC, tovernaar123 commented on commands/help.js
> +                data.push(`\`${semiPublic}\``);
not block but the indet is wierd

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +    name: 'playerdata',
mabye rename to playerdataJson and have the other one be playerdata

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +    required_role: role.board,
we shood allow this to be a function ngl

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +        //this command unlike its brother pd2 DOES require a name to be specified. You can still look up yourself but you must add in your username to look up.
why?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +            const fs  = require('fs');
put requirs at the top of the file above even the export

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +    execute(msg, args, _, internal_error) {
make this async (is import for fs.readfile not sync)

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +            let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
if you make the function async you read this with fs.readFile besides that i would really like to see some cache here as this file might become quit big

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +            let checkdata = mydata["PlayerData"][key1];
this can just be 
let checkdata = mydata["PlayerData"][name];

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +            if(mydata["PlayerData"][key1] )
this can be if(checkdata)

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +                finaldata = mydata["PlayerData"][key1]["Statistics"];
again you have checkdata you can use this here too checkdata["Statistics"]

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata.js
> +                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
you need to make sure this cant be more then 2000 chars just to be safe

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +    required_role: role.board,
again we shood make this allow a function so we can check if name is player name

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +    name: 'playerdata2',
if you rename the other one this can just be playerdata

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
could you add a comment on what this does?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +        function playerdata2command(name,msg,args)
this function shood not be inside the excute function

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +            if (1 == 1)
this is dumb

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    function ts(x) {
what does ts stand for?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                return 0;
make sure this return internal error of the error not just 0

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                        var msg_4 = [];
2 things never use var as it hoisted second, what does the name msg_4 mean their is only 1 message being sned right?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +
Again use let. Second check with an if if layout[i] exists if it does not set t1 to
Third what do these variable names mean.

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            var msg_3 = [];
Use let, what is msg_3?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            if (layout[i] == 'Playtime' || layout[i] == 'AfkTime') {
add some comments on what this is checking as it is confusing me :) .

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                var m1 = Math.floor(t1 % 60);
what is this doing?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                }
their needs to tell what h1 is and why it could be bigger the 0 and why we check this.

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            }
Again what are we doing here why are we calling ts with either msg_2[layout[i] or 0?
Also what does ts do? what does it return? why is it named ts? why is it an catch statement, is it going to error?
why will it error? so many questions

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            msg_4.push([msg_3[0], msg_3[1]]);
what is this?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
like pd json i would like it to asycn and use await readFile, also a cache might be nice

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let checkdata = mydata["PlayerData"][key1];
this can be  
let checkdata = mydata["PlayerData"][name];

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    finaldata = mydata["PlayerData"][key1]["Statistics"];
we can do 
finaldata = checkdata.Statistics

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let result = profile(item);
what does profile do onther comment might be nice here stating what it returns.

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let lookup = key1;
key1 is just the name you can just change this to name makes it more clear.

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                        }
why will it fail?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    channel.send(Embed2);
why not check if they are to big and only if they are send 2?

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                return;
you shood run internal_error here

2021-02-27 12:27 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    }
what does this do?

2021-02-27 12:27 UTC, tovernaar123 commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
No you can do command parsing in infobot.js

2021-02-27 16:53 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
thousand seperator

2021-02-27 16:54 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                    function ts(x) {
thousand seperator

2021-02-27 17:08 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                            msg_4.push([msg_3[0], msg_3[1]]);
push title and value in array

2021-02-27 17:08 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                            }
not all of the stuff have value inside.

2021-02-27 17:09 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                                }
we only need to show minutes when it is less than 1 hour of total time

2021-02-27 17:09 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                                var m1 = Math.floor(t1 % 60);
minutes to hours and minutes

2021-02-27 17:10 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                            if (layout[i] == 'Playtime' || layout[i] == 'AfkTime') {
only the value of playtime and afktime need to do some calculation

2021-02-27 17:11 UTC, PHIDIAS0303 commented on commands/playerdata2.js
> +                    channel.send(Embed2);
we are putting 0 in those cells, so it is fixed size

2021-04-08 18:31 UTC, aldldl commented on commands/help.js
> +                data.push(`\`${semiPublic}\``);
Not sure what you are saying, maybe I should reduce the indent here?

2021-04-08 18:32 UTC, aldldl commented on commands/playerdata.js
> +    name: 'playerdata',
I could see that.

2021-04-08 18:32 UTC, aldldl commented on commands/playerdata.js
> +    required_role: role.board,
I should know what that means, but I dont...

2021-04-08 19:08 UTC, aldldl reviewed
reviewed a bunch of stuff, made some suggested fixes in comments for final review, asked questions about questions I didn't understand.

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata.js
> +    execute(msg, args, _, internal_error) {
I copied this from a command you made, Not entirely sure how I can do that, do I just put async in front of it and it magically switches? @tovernaar123

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata.js
> +        //this command unlike its brother pd2 DOES require a name to be specified. You can still look up yourself but you must add in your username to look up.
I dont know, I think because I had to jump through alot of hoops for that and I already wrote this one.?.

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata.js
> +            if(mydata["PlayerData"][key1] )
```suggestion
            if(checkdata)
```
I think I meant that but forgot to change it after I added checkdata above

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata.js
> +                finaldata = mydata["PlayerData"][key1]["Statistics"];
```suggestion
                finaldata = checkdata["Statistics"];
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata.js
> +                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
```suggestion
                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
```
This should work to split it automatically. Though I will need to test it and then append the ```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +    required_role: role.board,
what allow? I thought I added an override to this file? Now I have to go see what I did.

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +        function playerdata2command(name,msg,args)
I believe you, but why?

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +            if (1 == 1)
This used to be a needed test, for some reason I did not want to lose the if statement so I made something that would always be true. Again I really should have commented that one because I don't remember why. Maybe because Phidas' code had it there and I tried to make it as plug and play as possible.

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                    function ts(x) {
```suggestion
                    function ts(x) { //thousands separator
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                                return 0;
I could be wrong but I think you want it as a number because it does math stuffs and *could* be 0 while still wanting the other math stuffs. we should ask @PHIDIAS0303

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                        var msg_4 = [];
```suggestion
                        let msg_4 = [];
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                            var msg_3 = [];
```suggestion
                            let msg_3 = [];
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                            if (layout[i] == 'Playtime' || layout[i] == 'AfkTime') {
```suggestion
                            if (layout[i] == 'Playtime' || layout[i] == 'AfkTime') { // Playtime and AfkTime are calculated, all others is taken as stored.
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +
```suggestion
                                try {
                                    let t1 = msg_2[layout[i]];
                                } catch (e) {
                                    let t1 = 0;
                                }
                                    
```
We need to ask @PHIDIAS0303 for more details on this one too

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                                var m1 = Math.floor(t1 % 60);
```suggestion
                                var h1 = Math.floor(t1 / 60); //the hours part of min-> hh:mm
                                var m1 = Math.floor(t1 % 60); // the min part of hh:mm
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                                }
```suggestion
                                if (h1 > 0) { // if hours (of hh:mm) is more than 0 then show how many hours you have, else only show mins below
                                    msg_3.push(layout_dict[layout[i]]);
                                    msg_3.push(h1 + ' h ' + m1 + ' m');
                                } else {
                                    msg_3.push(layout_dict[layout[i]]);
                                    msg_3.push(m1 + ' m ');
                                }
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                            msg_4.push([msg_3[0], msg_3[1]]);
```suggestion
                            msg_4.push([msg_3[0], msg_3[1]]); // push title and value in array
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                    let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
I think I need help with this part @tovernaar123

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                    finaldata = mydata["PlayerData"][key1]["Statistics"];
I tried that at one point, rather sure it didn't work for me... but I could have had other error at the same time as to why it didn't work.

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                    let lookup = key1;
```suggestion
                    let lookup = name;
```

2021-04-08 19:08 UTC, aldldl commented on commands/playerdata2.js
> +                return;
I think it does.
".catch((err) => { internal_error(err); return })"

2021-04-08 19:08 UTC, aldldl commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
what? this *is* infobot.js

2021-04-09 16:21 UTC, tovernaar123 commented on commands/help.js
> +                data.push(`\`${semiPublic}\``);
was probibly using mobile :)

2021-04-09 16:22 UTC, tovernaar123 commented on commands/playerdata.js
> +    required_role: role.board,
a function is a piece of code that has argument (like exucte) and then that function will rueturn true if the command can be run false if cant

2021-04-09 16:23 UTC, tovernaar123 commented on commands/playerdata.js
> +        //this command unlike its brother pd2 DOES require a name to be specified. You can still look up yourself but you must add in your username to look up.
gues its not to be bad it might be nice to allow .exp pd2

2021-04-09 16:25 UTC, tovernaar123 commented on commands/playerdata.js
> +    execute(msg, args, _, internal_error) {
yes

2021-04-09 16:27 UTC, tovernaar123 commented on commands/playerdata.js
> +            let checkdata = mydata["PlayerData"][key1];
yes and then also remove key1 =`${name}`

2021-04-09 16:28 UTC, tovernaar123 commented on commands/playerdata.js
> +            if(mydata["PlayerData"][key1] )
yes

2021-04-09 16:28 UTC, tovernaar123 commented on commands/playerdata.js
> +                finaldata = mydata["PlayerData"][key1]["Statistics"];
yes

2021-04-09 16:28 UTC, tovernaar123 commented on commands/playerdata.js
> +                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
no as then it wont have the ``` if its more then 2000

2021-04-09 16:29 UTC, tovernaar123 commented on commands/playerdata2.js
> +    required_role: role.board,
no i mean we shood make it possible to add a function as role so that its excutes code to check if somoen shood be able to run the command

2021-04-09 16:30 UTC, tovernaar123 commented on commands/playerdata2.js
> +        function playerdata2command(name,msg,args)
every time excute runs it waist recourses creating a function that does not use any arguments from the stack above it

2021-04-09 16:31 UTC, tovernaar123 commented on commands/playerdata2.js
> +            if (1 == 1)
this wont do anything just run the code, so please remove it to make it easier to read :)

2021-04-09 16:31 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    function ts(x) {
yes thats an good suggestion ^ also sorry for not seeing that

2021-04-09 16:32 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
what does that mean?

2021-04-09 16:33 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                return 0;
first of all this seems to really not need an try catch just make sure that if the function will error (like x not being a string) something like that that then it just returns 0

2021-04-09 16:34 UTC, tovernaar123 commented on commands/playerdata2.js
> +                        var msg_4 = [];
does not change why we have msg_4 what does msg_4 mean (but yes  the change of var to let is good)

2021-04-09 16:34 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            var msg_3 = [];
good but still want to know what msg_3 is

2021-04-09 16:35 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            if (layout[i] == 'Playtime' || layout[i] == 'AfkTime') {
yes okey good ^

2021-04-09 16:35 UTC, tovernaar123 commented on commands/playerdata2.js
> +
yes ^but the change to let is good

2021-04-09 16:36 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                var m1 = Math.floor(t1 % 60);
als use let, second many rename h1 to hours and m1 to minutes

2021-04-09 16:38 UTC, tovernaar123 commented on commands/playerdata2.js
> +                                }
makes sence what does not make sence

2021-04-09 16:41 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            }
@PHIDIAS0303 
```suggestion
                            } else {
                                    msg_3.push(layout_dict[layout[i]]);
                                    if(msg_2 && layout[i]) {
                                           msg_3.push(ts(msg_2[layout[i]]));
                                    }else{
                                            msg_3.push(ts(0));
                                    }
                            }
```

2021-04-09 16:41 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            }
second why do we need to call ts on 0 wont this always be the same?

2021-04-09 16:42 UTC, tovernaar123 commented on commands/playerdata2.js
> +                            msg_4.push([msg_3[0], msg_3[1]]);
titel of what, and which value

2021-04-09 16:47 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
```js
                    const fs = require('fs');
                    const util = require('util');
                    const readFile = util.promisify(fs.readFile);
                    let rawdata = await readFile('/home/exp_admin/api_v2/persistent_storage.json');
```

2021-04-09 16:48 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
this is not needed and a cache is just storing the data in memory so it can be read quicker

2021-04-09 16:48 UTC, aldldl commented on commands/playerdata2.js
> +                                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
1,000
1000
1.000
2 have thousands separated, one like American, one not at all, one like euro.

2021-04-09 16:49 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    finaldata = mydata["PlayerData"][key1]["Statistics"];
make sure its with a capital letter

2021-04-09 16:50 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    let lookup = key1;
why create onther varaible with the same value just change every place that uses lookup or key1 to name

2021-04-09 16:50 UTC, tovernaar123 commented on commands/playerdata2.js
> +                    channel.send(Embed2);
okey ^

2021-04-09 16:50 UTC, tovernaar123 commented on commands/playerdata2.js
> +                return;
i am blind

2021-04-09 16:51 UTC, tovernaar123 commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
cant* this is not allowed this will make the code unusable with more commands

2021-04-09 16:52 UTC, tovernaar123 commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
all command must follow a standart way of 1 file and not changes to infobot.js cause that will create a big mess :(

2021-04-13 21:28 UTC, aldldl commented on commands/playerdata.js
> +        //this command unlike its brother pd2 DOES require a name to be specified. You can still look up yourself but you must add in your username to look up.
Maybe We should create an issue and I'll do that after merge

2021-04-14 16:12 UTC, aldldl reviewed
fixed some more things

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +    execute(msg, args, _, internal_error) {
```suggestion
   async execute(msg, args, _, internal_error) {
```
done?

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +
```suggestion
            const fs  = require('fs');
```

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +            const fs  = require('fs');
```suggestion

```

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +            const fs  = require('fs');
done on line 3 now

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +            let rawdata = fs.readFileSync('/home/exp_admin/api_v2/persistent_storage.json');
I don't know how cache works.

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +            let checkdata = mydata["PlayerData"][key1];
```suggestion
            //key1 = `${name}`; // in dataFile ->-> commented out, will remove after testing. 
            let checkdata = mydata["PlayerData"][name];
```

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
will have to set up a check later, We should make an issue for this one then.

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata.js
> +                msg.channel.send(`${name}:\n\`\`\`json\n${JSON.stringify(finaldata, null, 2)}\`\`\``);
Will have to fix in new issue.

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +        function playerdata2command(name,msg,args)
Will create issue and do it after review is set

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +            if (1 == 1)
ok

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +                            msg_4.push([msg_3[0], msg_3[1]]);
title of json, then value of it

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +                    let checkdata = mydata["PlayerData"][key1];
```suggestion
                    //let key1 = `${name}`; // in dataFile // ->-> commented out till testing
                    //check data is the parsed data, but only the PlayerData, and that that matches the key1 (name)
                    let checkdata = mydata["PlayerData"][name];
```

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +                    finaldata = mydata["PlayerData"][key1]["Statistics"];
```suggestion
                    // OG Line -> finaldata = mydata["PlayerData"][key1]["Statistics"];
                    finaldata = checkdata.Statistics;
```

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +                    finaldata = mydata["PlayerData"][key1]["Statistics"];
ok

2021-04-14 16:12 UTC, aldldl commented on commands/playerdata2.js
> +                    let result = profile(item);
@PHIDIAS0303 do you know?

2021-04-14 16:12 UTC, aldldl commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
Fair but we need to add a standard way to check the role then... we had one but we wanted to allow ALL users to check their own name on an otherwise restricted command. I guess we open it up to everyone and restrict it in the command. I just did not want it to show up in help at first.

2021-04-14 17:51 UTC, aldldl commented on infoBot.js
> +            if(command.name == `playerdata` && args[0] == msg.member.displayName || command.name == `playerdata2` && args[0] == msg.member.displayName || command.name == `playerdata2` && !args[0])
Finished this for now, check out new code

2021-04-14 17:54 UTC, aldldl commented
I am going to close this pull request and create a new one, the code has changed so much the old comments don't really make sense anymore. Will need help with the file cache thing, but all else should be much better.

2021-04-14 17:54 UTC, closed without merging