Aldldl playerdata
tovernaar123/Exp-discord-bot pull request #34
Opened 2021-04-14 17:56 UTC by aldldl

Redid playerdata after a rename and change of AKA's and permissions. Please check this new PR as it should be much better. Still may need some help on the cache though.

2021-04-14 17:57 UTC, aldldl commented on infoBot.js
> +            //            {
```suggestion
```

2021-04-14 17:58 UTC, aldldl commented on infoBot.js
> +
```suggestion
```

2021-04-14 17:59 UTC, aldldl commented on infoBot.js
>          if (!allowed) {
```suggestion
        if (!allowed) {
        console.log(`Unauthorized `);
            msg.channel.send(`You do not have ${role.name} permission.`);
            return;
            }
```

2021-05-03 10:17 UTC, tovernaar123 requested changes
Lots of random try catches that make the code not so readable.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/discordpin.js
> +const { Role } = require("discord.js");
? why are you requiring role from discord.js?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/discordpin.js
> +const Discord = require('discord.js');
also see no reason to need a ref to discord

2021-05-03 10:17 UTC, tovernaar123 commented on commands/discordpinun.js
> +const { Role } = require("discord.js");
same no roles object in the discord module

2021-05-03 10:17 UTC, tovernaar123 commented on commands/discordpinun.js
> +const Discord = require('discord.js');
same you are not using this.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                                return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
the try catch here shood really not be needed

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                        let msg_4 = [];
please name you variables as to what they are msg_4 is not  very descriptive

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                                    var t1 = msg_2[layout[i]];
Why a try catch?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                                    var t1 = msg_2[layout[i]];
also what is t1 change the name of this variable

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                            let msg_3 = [];
what is msg_3 please change the name of this variable to smt more understandable.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                                if (isNaN(t1)) {
why would this be nan?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                                    msg_3.push(layout_dict[layout[i]]);
again no reason for a try catch, just test if layout[i] exsits and then if layout_dict[layout[i]].

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    const fs  = require('fs');
put all require on the top of the file

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    // set item to equal finaldata - to make Phidas formatting as plug and play as possible - not really needed otherwise
could also just be checkdata.Statistics.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    item = finaldata;
why are you renaming variables?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    let channel = msg.channel;
again what is the point of giving this a different name

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    let lookup = name;
same why does this need onther name

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                            Embed.addField(result[i][0], result[i][1], true);
please dont use try catch like this jus test if the array’s have the elments you want to use if not dont acces them

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                        try {
again no real reason for a try catch.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                    const Embed2 = new Discord.MessageEmbed();
please state what this really is, is this the second embed that will be sent?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                        try {
again why a try catch?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +                        try {
stop with all of these ty catch blocks :P .

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +    // required_role: role.board,
why is the not used?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdata.js
> +
what does this function do?

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdatajson.js
> +            const fs  = require('fs');
put it on the top.

2021-05-03 10:17 UTC, tovernaar123 commented on commands/playerdatajson.js
> +            let checkdata = mydata["PlayerData"][key1];
change key1 to name. and then remove key1 = name

2021-05-03 10:17 UTC, tovernaar123 commented on rcon_auto_connect.js
> +    let Iconnected = false;
i mean its fine by me but what does the I stand for?

2021-07-30 16:33 UTC, tovernaar123 commented
this shood not be merged to master and has already been put in dev

2021-07-30 16:33 UTC, closed without merging