main code cleanup
tovernaar123/Exp-discord-bot pull request #4
Opened 2020-10-12 19:11 UTC by tovernaar123

many things changed

2020-10-13 15:29 UTC, aldldl requested changes

2020-10-13 15:29 UTC, aldldl commented on commands/playersonline-new.js
> +            await msg.channel.send(`s${i+1} did not responde`);
```suggestion
            await msg.channel.send(`s${i+1} did not respond`); 
```

2020-10-13 15:29 UTC, aldldl commented on commands/playersonline-new.js
> +            msg.channel.send('Please pick a server first just a number (1-8). \`<#> <username> <reason>\`')
```suggestion
            msg.channel.send(`Please pick a server first. Just the number (1-8) or *all*.  Correct usage is \` po <server#>\``)
```

2020-10-13 15:29 UTC, aldldl commented on commands/playersonline-new.js
>              console.log(`Kick-Did not have server number`);
```suggestion
            console.log(`Players online - No server number provided`);
```

2020-10-13 15:29 UTC, aldldl commented on commands/playersonline-new.js
> +        if (server >= 1 && server <= 1) {
Maybe I'm missing this but I thought we fixed it earlier - should be > 1 <= 8 right?

```suggestion
        if (server >= 1 && server <= 8) {
```

2020-10-13 15:29 UTC, aldldl commented on commands/playersonline-new.js
> +            msg.reply(`Please pick a server first just a number (1-8) or *all*.  Correct usage is \` po <server#>\``)
```suggestion
            msg.reply(`Please pick a server first. Just the number (1-8) or *all*.  Correct usage is \` po <server#>\``)
```

2020-10-13 15:29 UTC, aldldl commented on botinfo.js
> +        msg.channel.send('Internal error in the command plz contact and admin')
```suggestion
        msg.channel.send('Internal error in the command. Please contact an admin')
```

2020-10-13 15:31 UTC, aldldl commented on commands/adminsonline.js
> +    aka: ['adminonline', 'adminsonline'],
```suggestion
    aka: ['adminonline', 'adminsonline', 'admins'],
```

2020-10-13 15:32 UTC, aldldl commented on commands/adminsonline.js
> +            server = Math.floor(args[0])
Can you explain what this means?

2020-10-13 15:33 UTC, aldldl commented on commands/adminsonline.js
> +        if (!server) { // Checks to see if the person specified a server number, then checks to see if the server number is part of the array of the servers it could be (1-8 currently)
This does not actually check the number anymore, it checks that there is not a blank.

2020-10-13 15:49 UTC, aldldl commented on commands/jail.js
> +            console.log('Server is 1-8');
```suggestion
            console.log('Server is ${server}');
```

2020-10-13 15:50 UTC, aldldl commented on commands/kick.js
> +    let reportChan = msg.guild.channels.cache.get('764881627893334047'); // Reports channel is "368812365594230788" for exp
```suggestion
    let reportChan = msg.guild.channels.cache.get('764881627893334047'); // Reports channel is "368812365594230788" for exp // Reports Channel is "764881627893334047" for test server
```

2020-10-13 15:53 UTC, aldldl commented on commands/log.js
>      description: 'get chat (last 10 lines) (Admin/Mod only command)',
```suggestion
    description: 'get chat (last 10 lines) (Board + only command)',
```

2020-10-13 15:55 UTC, aldldl commented on commands/log.js
> +            msg.channel.send('Please pick a server first just a number (1-8)')
```suggestion
            msg.channel.send('Please pick a server first. Just the number (1-8)')
```

2020-10-13 16:15 UTC, aldldl requested changes

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +async function runcommand(server, rcon, msg, to_un_jail) {
why to_un_jail when jail is toJail? kick is toKick

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +        await msg.channel.send(`**${to_un_jail}** has been jailed on S${server} for.`);
```suggestion
        await msg.channel.send(`**${to_un_jail}** has been unjailed on S${server}`);
```

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +        console.log(`${msg.author.username} has jailed ${to_un_jail} on S${server} for`);
```suggestion
        console.log(`${msg.author.username} has unjailed ${to_un_jail} on S${server}.`);
```

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +            console.log('Server is 1-8');
```suggestion
            console.log('Unjail server is S${server}');
```

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +            msg.reply(`Server number can\'t be bigger then 8 or smaller then 1. Correct usage is \` .exp unjail <server#> <username>\``)
```suggestion
            msg.reply(`Please pick a valid server first. Just the number (currently 1-8). Correct usage is \` unjail <server#> <username>\``)
```

2020-10-13 16:15 UTC, aldldl commented on commands/unjail.js
> +            console.log(`jail by ${msg.author.username} incorrect server number`);
```suggestion
            console.log(`unjail by ${msg.author.username} used the incorrect server number`);
```

2020-10-13 16:15 UTC, aldldl commented on infoBot.js
> +        msg.channel.send('Internal error in the command plz contact and admin')
```suggestion
        msg.channel.send('Internal error in the command. Please contact an admin.')
```

2020-10-13 16:15 UTC, aldldl commented on infoBot.js
> +let offline_servers = [2, 7]
Still not a fan of keeping 2 & 7 never connecting.

2020-10-13 16:15 UTC, aldldl commented on rcon_auto_connect.js
> +            setTimeout(connect, 10e3).unref();
Can we make longer, this spams the logs and seems too often, maybe 30 sec or 1 min?

2020-10-14 01:16 UTC, aldldl commented
Not sure if you saw but I did a second code review shortly after the first one for the other files

2020-10-14 12:40 UTC, tovernaar123 commented on commands/adminsonline.js
> +            server = Math.floor(args[0])
if(!isNaN(server)){ (so if the server is a number
floor the number so 5.5 becomes 5 as we dont want to be able acces s5.5 :P

2020-10-14 12:40 UTC, tovernaar123 commented on commands/adminsonline.js
> +        if (!server) { // Checks to see if the person specified a server number, then checks to see if the server number is part of the array of the servers it could be (1-8 currently)
well i still check if it exsits but the comment is wrong ye

2020-10-14 12:40 UTC, tovernaar123 commented on commands/jail.js
> +            console.log('Server is 1-8');
this wont work as the the string with ${} vars has to be with `something here ` not 'some thing here' altough i will change it

2020-10-14 12:40 UTC, tovernaar123 commented on commands/unjail.js
> +async function runcommand(server, rcon, msg, to_un_jail) {
yeah could have been toUnjail but the o next to the u looks wierd :P

2020-10-14 12:40 UTC, tovernaar123 commented on commands/unjail.js
> +            console.log('Server is 1-8');
again '' does not allow for ${var} (will change it though)

2020-10-14 12:40 UTC, tovernaar123 commented on infoBot.js
> +let offline_servers = [2, 7]
might make a command to make it so you can disable or enable them

2020-10-14 12:40 UTC, tovernaar123 commented on rcon_auto_connect.js
> +            setTimeout(connect, 10e3).unref();
yep k

2020-10-14 12:43 UTC, tovernaar123 commented on commands/playersonline-new.js
> +        if (server >= 1 && server <= 1) {
this file has been deleted lol

2020-10-14 12:50 UTC, tovernaar123 commented
shood be all fixed

2020-10-14 17:06 UTC, merged